DROP INDEX IF EXISTS idx_comments_path_created;
DROP INDEX IF EXISTS idx_comments_post_parent_created;
DROP INDEX IF EXISTS idx_comments_created_at;
DROP INDEX IF EXISTS idx_comments_level;
DROP INDEX IF EXISTS idx_comments_path;
DROP INDEX IF EXISTS idx_comments_parent_id;
DROP INDEX IF EXISTS idx_comments_author_id;
DROP INDEX IF EXISTS idx_comments_post_id;
DROP TABLE IF EXISTS comments;