// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	 "ozon-posts/internal/entities"
)

type CommentConnection struct {
	Comments   []*entities.Comment `json:"comments"`
	Pagination *PaginationInfo     `json:"pagination"`
}

type CommentEvent struct {
	Type    string            `json:"type"`
	PostID  string            `json:"postId"`
	Comment *entities.Comment `json:"comment"`
}

type CreateCommentInput struct {
	PostID   string  `json:"postId"`
	AuthorID string  `json:"authorId"`
	Content  string  `json:"content"`
	ParentID *string `json:"parentId,omitempty"`
}

type CreatePostInput struct {
	AuthorID string `json:"authorId"`
	Title    string `json:"title"`
	Content  string `json:"content"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type Mutation struct {
}

type PaginationInfo struct {
	Total   int  `json:"total"`
	Limit   int  `json:"limit"`
	Offset  int  `json:"offset"`
	HasMore bool `json:"hasMore"`
}

type PostConnection struct {
	Posts      []*entities.Post `json:"posts"`
	Pagination *PaginationInfo  `json:"pagination"`
}

type Query struct {
}

type Subscription struct {
}

type ToggleCommentsInput struct {
	PostID   string `json:"postId"`
	AuthorID string `json:"authorId"`
	Disable  bool   `json:"disable"`
}

type UpdateCommentInput struct {
	ID       string `json:"id"`
	AuthorID string `json:"authorId"`
	Content  string `json:"content"`
}

type UpdatePostInput struct {
	ID       string `json:"id"`
	AuthorID string `json:"authorId"`
	Title    string `json:"title"`
	Content  string `json:"content"`
}

type UpdateUserInput struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
